source "https://rubygems.org"

gem "jekyll", "~> 3.0"
gem "jekyll-sitemap"
gem "jekyll-gist"
# gem "octopress"
gem "kramdown-parser-gfm"
gem "jekyll-include-cache"
gem "jekyll-paginate"
gem "jekyll-feed"